name: html
version: 0.13.4-dev

description: A library for working with HTML documents.
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/html

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  csslib: '>=0.13.2 <0.15.0'
  source_span: '>=1.0.0 <2.0.0'
  utf: '>=0.9.0 <0.10.0'

dev_dependencies:
  path: ^1.6.2
  pedantic: ^1.3.0
  test: ^1.3.0
