name: html
version: 0.14.0+3

description: APIs for parsing and manipulating HTML content outside the browser.
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/html

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  csslib: '>=0.13.2 <0.17.0'
  source_span: '>=1.0.0 <2.0.0'

dev_dependencies:
  path: ^1.6.2
  pedantic: ^1.3.0
  test: ^1.3.0
