name: html
version: 0.15.5-wip
description: APIs for parsing and manipulating HTML content outside the browser.
repository: https://github.com/dart-lang/html

topics:
  - html
  - web

environment:
  sdk: ^3.2.0

dependencies:
  csslib: ^1.0.0
  source_span: ^1.8.0

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
  path: ^1.8.0
  test: ^1.16.6
